### ISSUE TITLE
[Exception] File not found

### ISSUE THREAD

**Issue by SelenaZelia** [frank184/FreeEditor#2]
Alright, the printer is nearly done I'll pull request that in some minutes !
But each time I launch the Editor in Eclipse, I got a file not found exception. I guess there's a problem with the "LAST_FILE" constant in FreeEditorFrame, don't have alot of time right now to investigate but wanted to tell it !

**Comment by frank184** [comment]
Hey awesome to see you put in some time on this project!

The LAST_FILE is the file called lastFile in the project. 

In Eclipse, this should go in the project directory.

If this file is missing, the exception will occur. An alternative would be to catch that exception and to generate a new lastFile file.

Hope this helps! And thanks again!

**Comment by SelenaZelia** [comment]
Awesome to see someone working on that kind of project ! It feels nice to see some "little" project growing stable and strong when you only see big "ideas" that are finally abandonned after some days !

Alright I'll try to get something working to create the next lastFile in a couple of days !

**Comment by frank184** [comment]
Hahaha I like these kind of projects too!

For the File exception, I checked your repo and saw that lastFile is present. The issue is that the "last file" refers to a file from my PC "C:\Users\GameTop\Documents\test.txt". 

It can be discarded from the repo because the app generates this file if not NotFound and in the future should simply be emptied whenever the reference in the file is NotFound.

**Comment by frank184** [comment]
Fixed!

**Comment by SelenaZelia** [comment]
Oh alright, didn't took much time to look, nice ! :)
